내 정보
battleent/nft-platform-prototype pull request #14
Opened 2021-10-08 09:17 UTC by moneekim

내 정보 화면에서 하단 비밀번호 변경 부분 구현했습니다.

2021-10-14 05:16 UTC, doh98 requested changes
닉네임/언어/국가 설정 form과 비밀번호 변경 form은 별도의 form입니다. 폼 하나당 하나의 `useForm`을 사용해야 합니다.

submit시의 처리 로직도 컴포넌트에서 분리하는게 좋습니다.

2021-10-14 05:16 UTC, doh98 commented on src/pages/my/index.tsx
> +  const { register, handleSubmit } = useForm<MyProps>({ defaultValues });
API에서 내려주는 유저의 정보 모델과 form에서 다뤄야 할 값들은 다릅니다.
useForm에서는 실제로 유저가 form에 입력하게 될 내용들이 들어가면 좋을 것 같습니다.

2021-10-14 08:52 UTC, MoKyungKim commented
- interface 이름 변경
- form 분리
- UserData에 유저가 form에 입력하게 될 항목으로만 수정했습니다. 
form 분리하고 return하는 부분에서 분리할 수 있는 것들을 컴포넌트로 분리하는걸 제대로 한건지 확인 부탁드립니다.

2021-10-15 03:06 UTC, doh98 commented on src/pages/my/index.tsx
> +                  lck@battleent.com
유저 정보에 있는 값을 사용해주세요.

2021-10-15 03:48 UTC, doh98 commented on src/pages/my/index.tsx
> +    useForm<ProfileData>();
다른 폼끼리는 다른 타입을 사용해야 하지 않을까요?

2021-10-15 06:26 UTC, merged